stages:
  - triggers

trigger_provision:
  stage: triggers
  trigger:
    include: HRWSI_System/.system_gitlab-ci.yml
  rules:
    - changes:
        - HRWSI_System/**/**/*
        - test/HRWSI_System/**/**/**/**/*

trigger_database:
  stage: triggers
  trigger:
    include: HRWSI_Database/.database_gitlab-ci.yml
  rules:
    - changes:
        - HRWSI_Database/**/**/*

trigger_cloud_provision:
  stage: triggers
  trigger:
    include: HRWSI_Deployment/provision/.provision_gitlab-ci.yml
  rules:
    - changes:
        - HRWSI_Deployment/provision/**/*